accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'


urlpatterns =[
    path('register/' , views.RegisterView.as_view(), name='Register'),
    path('login/' , views.LoginView.as_view(), name='Login'),
    path('logout/' , views.LogoutView.as_view(), name='Logout'),
    path('profile/<int:user_id>/' , views.UserProfileView.as_view(), name='Profile'),
    path('password-reset/',  views.UserPasswordResetView.as_view(),name='reset_password'),
    path('password-reset/done/',views.UserPasswordResetDoneView.as_view() ,name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('follow/<int:user_id>/' ,views.UserFollowView.as_view() , name='Follow'),
    path('unfollow/<int:user_id>/',views.UserUnfollowView.as_view(), name='Unfollow'),
    path('edit/' ,views.EditProfileView.as_view(), name='Edit_profile'),
   
]
    

core/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name ='home'


urlpatterns = [
    path('home/',views.HomeView.as_view() , name='home'),
    path('post/<int:post_id>/<slug:post_slug>/' , views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/'  , views.PostDeleteView.as_view() , name='post_delete'),
    path('post/create/' , views.PostCreateView.as_view(), name='post_create'),
    path('post/update/<int:post_id>' , views.PostUpdateView.as_view(), name='post_update'),
    path('reply/<int:post_id>/<int:comment_id>/' , views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/' , views.LikeView.as_view(),name='Like'),

]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from accounts.models import Post , Comment
from django import forms



class PostUpdateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('body',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('body',)
        widgets={
            'body':forms.Textarea(attrs={'class':'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('body',)



class PostSearchForm(forms.Form):
    search=forms.CharField()
   

home/views.py
from typing import Any
from django import http
from django.http.response import HttpResponse
from django.shortcuts import render , redirect ,get_object_or_404
from django.views import View
from accounts.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import *
from django.utils.text import slugify 
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    form_class=PostSearchForm

    def get(self , request):
        posts=Post.objects.all()
        if request.GET.get('search'):
            posts=posts.filter(body__contains=request.GET['search'])
        return render(request , 'home/index.html' ,{'posts':posts ,'form':self.form_class})
    


class PostDetailView(View):
    form_class=CommentCreateForm
    form_reply_class = CommentReplyForm

    def setup(self , request , *args , **kwargs):
        self.post_instance = get_object_or_404(Post ,pk=kwargs['post_id'] , slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)


    def get(self , request,post_id , post_slug):
        comments = self.post_instance.post_comments.filter(is_reply=False)
        can_like=False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like=True
        return render(request , 'home/detail.html',{'post':self.post_instance ,'comments':comments ,                                
        'form':self.form_class ,'form_reply':self.form_reply_class ,'can_like':can_like})
    
    @method_decorator(login_required)
    def post(self , request ,*args ,**kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            commentt=form.save(commit=False)
            commentt.user = request.user
            commentt.post = self.post_instance
            commentt.save()
            messages.success(request,'your comment submitted' ,'success')
            return redirect('home:post_detail',self.post_instance.id  , self.post_instance.slug)
    
class PostDeleteView(LoginRequiredMixin,View):
    def get(self , request , post_id ):
        post=get_object_or_404(Post , pk=post_id )
        if request.user.id == post.user.id:
            post.delete()
            messages.success(request , 'post deleted' ,'success')
        else:
            messages.error(request,'post cant deleted' , 'warning')
        return redirect('home:home')



class PostUpdateView(LoginRequiredMixin,View):
    form_class=PostUpdateForm 


    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request,*args,**kwargs)
    


    def dispatch(self, request, *args , **kwargs) :
        post = Post.objects.get(pk=kwargs['post_id'])
        if not request.user.id == post.user.id :
            messages.error(request, 'not allowed' , 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    



    def get(self, request, *args, **kwargs):
        post =self.post_instance
        form=self.form_class(instance=post)
        return render(request ,'home/update.html',{'form':form})



    def post(self, request, *args, **kwargs):
        post=self.post_instance
        form=self.form_class(request.POST , instance=post)
        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.slug=slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request ,'post is updated' , 'success')
            return redirect('home:post_detail',post.id , post.slug)




  
        
class PostCreateView(LoginRequiredMixin , View):
    form_class = PostUpdateForm

    def get(self , request,*args ,**kwargs):
        form = self.form_class
        return render(request,'home/create.html',{'form':form})
    
    def post(self , request,*args ,**kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.slug=slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request ,'new post created','success')
            return redirect('home:post_detail',new_post.id ,new_post.slug)

class PostAddReplyView(LoginRequiredMixin , View):
    form_class = CommentReplyForm

    def post(self,request, *args , **kwargs):
        post=get_object_or_404(post, id=kwargs['post_id'])
        Comment=get_object_or_404(Comment,id=kwargs['comment_id'])
        form = self.form_class(request.POST)
        if form.is_valid():
            reply=form.save(commit=False)
            reply.user=request.user
            reply.post=post
            reply.reply=Comment
            reply.is_reply=True
            reply.save()
            messages.success(request ,'reply submitted','success')
        return redirect('home:post_detail',post.id , post.slug)
    

class LikeView(LoginRequiredMixin,View):
    def get(self , request ,post_id):
        post=get_object_or_404(Post , id=post_id)
        like=Vote.objects.filter(post=post , user=request.user)
        if like.exists():
            messages.error(request,'you liked this post','danger')
        else:
            Vote(post=post , user=request.user).save()
            messages.success(request, 'like successfully','success')
        return redirect('home:post_detail',post.id , post.slug)
    

home/templates/home/create.html
{% extends 'base.html'%}

{% block content%}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="create">
    </form>

{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.id == post.user.id %}
    <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}
    <p><a href="{% url 'accounts:Profile' post.user.id %}"> {{post.user.username}}</a> -{{post.updated_date|date:"Y-M-d-D"}}</p>
    <p>{{post.body}}</p><hr>

    {% if request.user.is_authenticated %}
        <a href="{% url 'home:Like' post.id %}"class="{% if can_like %} disabled {% endif %} btn btn-primary">like {{post.likes_count}}</a>

        
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="send">
        </form><br/>
    {% else %}
        <p class="alert alert-danger">please login first </p>
    {% endif %}



   
    <p>{{comments.count}} comments</p>
   
    {% for comment in comments %}
        <div class="card">
            <p class="card-header">{{comment.user}} \ {{comment.created_date|timesince}}</p>
            <p class="card-body">{{comment.body}}</p>

            {% if request.user.is_authenticated %}
                <form action="{% url 'home:add_reply' post.id comment.id %}" method="post" style="display:none;" >
                    {% csrf_token %}
                    {{form_reply.as_p}}
                    <input type="submit" value="send">
                </form><br/>
            {% endif %}


            {% for reply in comment.reply_comments.all %}
                <p class="bg-primary p-3 m-2 ">{{reply.user}} <br/> {{reply.body }} </p>
            {% endfor %}
        </div><br/>
    {% empty %}
        <p>No comments yet</p>
    {% endfor %}
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="get">
        {{form.as_p}}
        <input type="submit" value="search">
    </form><br/><br/>


    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{post.body|truncatewords:8}}</a>
        {% endfor %}

    </div>

{% endblock %}

home/templates/home/update.html
{% extends 'base.html'%}

{% block content%}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update">
    </form>

{% endblock %}