accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'


urlpatterns =[
    path('register/' , views.RegisterView.as_view(), name='Register'),
    path('login/' , views.LoginView.as_view(), name='Login'),
    path('logout/' , views.LogoutView.as_view(), name='Logout'),
    path('profile/<int:user_id>/' , views.UserProfileView.as_view(), name='Profile'),
    path('password-reset/',  views.UserPasswordResetView.as_view(),name='reset_password'),
    path('password-reset/done/',views.UserPasswordResetDoneView.as_view() ,name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password-reset-complete/',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('follow/<int:user_id>/' ,views.UserFollowView.as_view() , name='Follow'),
    path('unfollow/<int:user_id>/',views.UserUnfollowView.as_view(), name='Unfollow'),
    path('edit/' ,views.EditProfileView.as_view(), name='Edit_profile'),
   
]
    

core/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name ='home'


urlpatterns = [
    path('home/',views.HomeView.as_view() , name='home'),
    path('post/<int:post_id>/<slug:post_slug>/' , views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/'  , views.PostDeleteView.as_view() , name='post_delete'),
    path('post/create/' , views.PostCreateView.as_view(), name='post_create'),
    path('post/update/<int:post_id>' , views.PostUpdateView.as_view(), name='post_update'),
    path('reply/<int:post_id>/<int:comment_id>/' , views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/' , views.LikeView.as_view(),name='Like'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image

class Post(models.Model):
    user=models.ForeignKey(User , on_delete=models.CASCADE , related_name='posts')
    body=models.TextField()
    slug=models.SlugField()
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_date','body')


    def __str__(self):
        return f'{self.slug} - {self.updated_date}'
    

    def get_absolute_url(self):
        return reverse('home:post_detail' , args=(self.id , self.slug))
    
    def likes_count(self):
        return self.post_votes.count()
    
    def user_can_like(self , user):
        user_like=user.user_Votes.filter(post=self)
        if user_like.exists():
            return True
        return False
    

class Relation(models.Model):
    user_who_follower=models.ForeignKey(User , on_delete=models.CASCADE,related_name='followers')
    user_who_following=models.ForeignKey(User,on_delete=models.CASCADE, related_name='followings')
    created_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user_who_follower} start following {self.user_who_following}' 
    


class Comment(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE ,related_name='user_comments')
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name='post_comments' )
    reply=models.ForeignKey('comment',on_delete=models.CASCADE , related_name='reply_comments', blank=True , null=True)
    is_reply=models.BooleanField(default=False)
    body=models.TextField(max_length=450)
    created_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.body[:30]}"
    



class Vote(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE , related_name='user_Votes')
    post=models.ForeignKey(Post , on_delete=models.CASCADE , related_name='post_votes')

    def __str__(self):
        return f"{self.user} liked {self.post.slug}"
    


   
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio=models.CharField(max_length=200 , null=True , blank=True)
    link=models.URLField(null=True , blank=True)
   

accounts/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from accounts.models import Profile

class RegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='confirm password',widget=forms.PasswordInput(attrs={'class':'form-control'}))


    def clean_email(self):
        email=self.cleaned_data['email']
        user =User.objects.filter(email=email).exists()
        if user :
            raise ValidationError('this user already exist ')
        return email
    
    def clean(self):
        data=super().clean()
        p1=data.get('password')
        p2= data.get('password2')
        
        if p1 and p2 and p1 != p2:
            raise ValidationError('passwords must match')
        

class LoginForm(forms.Form):
     username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
     password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class EditProfileForm(forms.ModelForm):
    email=forms.EmailField()

    class Meta:
        model=Profile
        fields=('bio', 'link')

accounts/views.py
from typing import Any
from django import http
from django.shortcuts import render , redirect ,get_object_or_404
from django.views import View
from .forms import *
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate , login , logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class RegisterView(View):
    form_class = RegistrationForm

    def dispatch(self, request , *args, **kwargs) :
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request,*args ,**kwargs)
    
    def get(self , request):
        form =self.form_class()
        return render(request ,'accounts/register.html' ,{'form':form})
    
    def post(self, request):
        form=self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            User.objects.create_user(data['username'],data['email'],data['password'])
            messages.success(request,'user creation success' ,'success')
            return redirect('home:home')
        return render(request , 'accounts/register.html' , {'form':form})
    


class LoginView(View):
    form_class =LoginForm
    template_name = 'accounts/login.html'

    def setup(self , request , *args , **kwargs):
        self.next=request.GET.get('next')
        return super().setup(request, *args, **kwargs)


    def dispatch(self, request , *args, **kwargs) :
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request,*args ,**kwargs)
    

    def get(self , request):
        form = self.form_class()
        return render(request , self.template_name , {'form':form})
    
    def post(self , request):
        form=self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request , username =data['username'] ,password = data['password'])
            if user is not None:
                login(request , user)
                messages.success(request , 'login successfully','success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.error(request ,'password or username is wrong' ,'warning')
        return render(request , self.template_name ,{'form':form})



class LogoutView( LoginRequiredMixin,View):
    def get(self , request):
        logout(request)
        messages.success(request ,'logout successfully','success')
        return redirect('home:home')
    

class UserProfileView(LoginRequiredMixin,View):
    template_name = 'accounts/profile.html'
    def get(self , request , user_id):
        now_following=False
        user = get_object_or_404(User,pk=user_id)
        posts =user.posts.all()
        relation=Relation.objects.filter(user_who_follower=request.user , user_who_following=user_id).exists()
        if relation :
            now_following=True
        return render(request , self.template_name , {'user':user ,'posts':posts ,'now_following':now_following})



class  UserPasswordResetView(auth_views.PasswordResetView):
    template_name='accounts/password_reset_form.html'
    success_url=reverse_lazy('accounts:password_reset_done')
    email_template_name='accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'accounts/password_reset_done.html'



class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name='accounts/password_reset_confirm.html'
    success_url =reverse_lazy('accounts:password_reset_complete')


class  UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name='accounts/password_reset_complete.html'



class UserFollowView(LoginRequiredMixin,View):
    def get(self,request, *args ,**kwargs):
        user=User.objects.get(id=kwargs['user_id'])
        relation=Relation.objects.filter( user_who_follower=request.user , user_who_following=user)
        if relation.exists():
            messages.error(request,'you are following this user','success')
        else:
            Relation(user_who_follower=request.user , user_who_following=user).save()
            messages.success(request,'you start following this user','success')
        return redirect('accounts:Profile',user.id)




class UserUnfollowView(LoginRequiredMixin,View):
    def get(self,request, *args ,**kwargs):
        user=User.objects.get(id=kwargs['user_id'])
        relation=Relation.objects.filter(user_who_follower=request.user , user_who_following=user)
        if relation.exists():
            relation.delete()
            messages.success(request ,'unfollowing successfully','success')
        else:
            messages.error(request,'you are not following this user','danger')
        return redirect('accounts:Profile', user.id)




class EditProfileView(LoginRequiredMixin , View):
    form_class=EditProfileForm

    def get(self , request):
        form=self.form_class(instance=request.user.profile , initial={'email':request.user.email})
        return render(request,'accounts/Edit_profile.html' ,{'form':form})
    
    def post(self , request):
        form=self.form_class(request.POST , instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email=form.cleaned_data['email']
            request.user.save()
            messages.success(request,'profile was edited','success')
        return redirect('accounts:Profile' ,request.user.id)

accounts/templates/accounts/Edit_profile.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Edit">
    </form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h2> Login</h2>

    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='login'>

    </form>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{%extends 'base.html'%}

{%block content%}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'accounts:Login' %}">Login</a></p>
</div>
 	
{%endblock content%}

accounts/templates/accounts/password_reset_confirm.html
{%extends 'base.html'%}

{%block content%}

<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>


{%endblock content%}

accounts/templates/accounts/password_reset_done.html
{%extends 'base.html'%}

{%block content%}

<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
</div>

{%endblock content%}

accounts/templates/accounts/password_reset_email.html
<p>Hi</p>

<p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>

<p>Please click the following link to reset your password:</p>

{{ protocol }}://{{ domain }}{% url "accounts:password_reset_confirm" uidb64=uid token=token %}

<p>Thanks</p>
<p>Todo App Team</p>

accounts/templates/accounts/password_reset_form.html
{%extends 'base.html'%}

{%block content%}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons">
			<input type="submit" value="Send" class="btn btn-primary">
			<a href="{%url 'accounts:Login' %}"  class="btn btn-outline">Cancel</a>
		</div>
	</form>
	</div>
{%endblock content%}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-center"> {{user.username}}</h2>
    <h2 class="text-center">{{user.profile.bio}}</h2>
    <h2 class="text-center">{{user.profile.link}}</h2>
    
    
   

    {% if request.user.id == user.id %}
        <a href="{% url 'home:post_create' %}" class="btn btn-primary"> Create </a>
        <a href="{% url 'accounts:Edit_profile' %}" class="btn btn-info"> Edit_profile</a>

    {% endif %}

    {% if request.user.id != user.id and not now_following %}
        <a class="btn btn-primary" href="{% url 'accounts:Follow' user.id %}">Follow</a>
    {% elif request.user.id != user.id and now_following %} 
        <a class="btn btn-primary" href="{% url 'accounts:Unfollow' user.id %}">Unfollow</a>
    {% endif %}
    

    
    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{post.body|truncatewords:8}}</a>
        {% endfor %}

    </div>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <h2> Registration</h2>

    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='register'>

    </form>
{% endblock %}